Fix CI

diff --git a/.github/workflows/build-and-test-template.yml b/.github/workflows/build-and-test-template.yml
--- a/.github/workflows/build-and-test-template.yml
+++ b/.github/workflows/build-and-test-template.yml
@@ -28,62 +28,66 @@ on:
         type: string
 
 jobs:
-  # build-devcontainer-linux:
-  #   name: "Build and test: ${{ matrix.host.os }}/${{ inputs.build-type }}"
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       host: [
-  #         { type: linux, os: ubuntu-latest,
-  #           build-options: "-v --build-tests -Xswiftc -enable-testing",
-  #           test-options: "-v --enable-code-coverage"
-  #         }
-  #       ]
-  #       configuration: [ "debug", "release" ]
+  build-devcontainer-linux:
+    name: "Build and test: ${{ matrix.host.os }}/${{ inputs.build-type }}"
+    strategy:
+      fail-fast: false
+      matrix:
+        host: [
+          { type: linux, os: ubuntu-latest,
+            build-options: "--build-tests -Xswiftc -enable-testing",
+            test-options: "--enable-code-coverage"
+          }
+        ]
+        # configuration: [ "debug", "release" ]
 
-  #   runs-on: ${{ matrix.host.os }}
-  #   steps:
-  #   - uses: actions/checkout@v3
+    runs-on: ${{ matrix.host.os }}
+    steps:
+    - uses: actions/checkout@v3
+      with:
+        submodules: 'true'
 
-  #   - uses: actions/cache@v3
-  #     with:
-  #       path: .build
-  #       key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
-  #       restore-keys: |
-  #         ${{ runner.os }}-spm-
+    - uses: actions/cache@v3
+      with:
+        path: .build
+        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
+        restore-keys: |
+          ${{ runner.os }}-spm-
 
-  #   - name: Build and Test
-  #     uses: devcontainers/ci@v0.3
-  #     with:
-  #       runCmd: |
-  #         set -eo pipefail
-  #         swift package resolve
-  #         .build/checkouts/Swifty-LLVM/Tools/make-pkgconfig.sh llvm.pc
-  #         export PKG_CONFIG_PATH=$PWD
-  #         swift build -c ${{ inputs.build-type }} ${{ matrix.host.build-options }}
-  #         BUILD_DIR=$(swift build -c ${{ inputs.build-type }} --show-bin-path)
-  #         echo "BUILD_DIR=$BUILD_DIR" >> $GITHUB_ENV
-  #         # swift test -c ${{ inputs.build-type }} ${{ matrix.host.test-options }} |
-  #         #   tee testoutput.txt && (
-  #         #     (grep -q "[.']EndToEndTests[/. ]test_" testoutput.txt && grep -q "[.']HyloTests[/. ]test_" testoutput.txt) ||
-  #         #     (echo "error: generated tests failed to run; see
-  #         #     https://github.com/apple/swift-package-manager/issues/6595" && false) )
+    - name: Build and Test
+      uses: devcontainers/ci@v0.3
+      with:
+        runCmd: |
+          set -eo pipefail
+          cd hylo
+          swift package resolve
+          .build/checkouts/Swifty-LLVM/Tools/make-pkgconfig.sh llvm.pc
+          export PKG_CONFIG_PATH=$PWD
+          cd ..
+          swift build -c ${{ inputs.build-type }} ${{ matrix.host.build-options }}
+          BUILD_DIR=$(swift build -c ${{ inputs.build-type }} --show-bin-path)
+          echo "BUILD_DIR=$BUILD_DIR" >> $GITHUB_ENV
+          # swift test -c ${{ inputs.build-type }} ${{ matrix.host.test-options }} |
+          #   tee testoutput.txt && (
+          #     (grep -q "[.']EndToEndTests[/. ]test_" testoutput.txt && grep -q "[.']HyloTests[/. ]test_" testoutput.txt) ||
+          #     (echo "error: generated tests failed to run; see
+          #     https://github.com/apple/swift-package-manager/issues/6595" && false) )
 
-  #   # - name: Check code coverage
-  #   #   uses: mattpolzin/swift-codecov-action@0.7.3
-  #   #   with:
-  #   #     SORT_ORDER: +cov
-  #   #     MINIMUM_COVERAGE: 84
-  #   #     CODECOV_JSON: .build/${{ inputs.build-type }}/codecov/*.json
+    # - name: Check code coverage
+    #   uses: mattpolzin/swift-codecov-action@0.7.3
+    #   with:
+    #     SORT_ORDER: +cov
+    #     MINIMUM_COVERAGE: 84
+    #     CODECOV_JSON: .build/${{ inputs.build-type }}/codecov/*.json
 
 
-  #   - name: Upload Hylo LSP artifacts (${{ inputs.build-type }})
-  #     uses: actions/upload-artifact@v3
-  #     with:
-  #       name: hylo-lsp-artifacts-linux
-  #       path: |
-  #         ${{ env.BUILD_DIR }}/hylo-lsp-client
-  #         ${{ env.BUILD_DIR }}/hylo-lsp-server
+    - name: Upload Hylo LSP artifacts (${{ inputs.build-type }})
+      uses: actions/upload-artifact@v3
+      with:
+        name: hylo-lsp-artifacts-linux
+        path: |
+          ${{ env.BUILD_DIR }}/hylo-lsp-client
+          ${{ env.BUILD_DIR }}/hylo-lsp-server
 
   build-native-macos:
     name: "Build and test: ${{ matrix.host.os }}/${{ inputs.build-type }}"
@@ -95,7 +99,7 @@ jobs:
             type: macos, os: macos-13,
             build-options: "--build-tests -Xswiftc -enable-testing",
             # No coverage support on MacOS
-            test-options: "-v"
+            test-options: ""
           }
         ]
         swift: [
