.

diff --git a/.github/workflows/build-and-test-template.yml b/.github/workflows/build-and-test-template.yml
--- a/.github/workflows/build-and-test-template.yml
+++ b/.github/workflows/build-and-test-template.yml
@@ -137,15 +137,16 @@ jobs:
         swift build -c ${{ inputs.build-type }} ${{ matrix.host.build-options }}
         BUILD_DIR=$(swift build -c ${{ inputs.build-type }} --show-bin-path)
         echo "BUILD_DIR=$BUILD_DIR" >> $GITHUB_ENV
-    - name: Test (${{ inputs.build-type }})
-      run: |
-        set -eo pipefail
-        export PKG_CONFIG_PATH=$PWD/hylo
-        swift test -c ${{ inputs.build-type }} ${{ matrix.host.test-options }} |
-          tee testoutput.txt && (
-            (grep -q "[.']EndToEndTests[/. ]test_" testoutput.txt && grep -q "[.']HyloTests[/. ]test_" testoutput.txt) ||
-            (echo "error: generated tests failed to run; see
-            https://github.com/apple/swift-package-manager/issues/6595" && false) )
+
+    # - name: Test (${{ inputs.build-type }})
+    #   run: |
+    #     set -eo pipefail
+    #     export PKG_CONFIG_PATH=$PWD/hylo
+    #     swift test -c ${{ inputs.build-type }} ${{ matrix.host.test-options }} |
+    #       tee testoutput.txt && (
+    #         (grep -q "[.']EndToEndTests[/. ]test_" testoutput.txt && grep -q "[.']HyloTests[/. ]test_" testoutput.txt) ||
+    #         (echo "error: generated tests failed to run; see
+    #         https://github.com/apple/swift-package-manager/issues/6595" && false) )
 
     - name: Upload Hylo LSP artifacts (${{ inputs.build-type }})
       uses: actions/upload-artifact@v3
@@ -200,12 +201,18 @@ jobs:
     #     $BUILD_DIR = swift build -c ${{ inputs.build-type }} --show-bin-path
     #     xcopy $BUILD_DIR artifacts /I
 
-    - name: Upload Hylo LSP artifacts (${{ inputs.build-type }})
+    - name: Upload Swift artifacts
       uses: actions/upload-artifact@v3
       with:
         name: hylo-lsp-artifacts-windows
         path: |
           C:\Program Files\Swift\runtime-development\usr\bin
+
+    - name: Upload Hylo LSP artifacts (${{ inputs.build-type }})
+      uses: actions/upload-artifact@v3
+      with:
+        name: hylo-lsp-artifacts-windows
+        path: |
           ${{ env.BUILD_DIR }}/hylo-lsp-client.exe
           ${{ env.BUILD_DIR }}/hylo-lsp-server.exe
 
