.

diff --git a/.github/workflows/build-and-test-template.yml b/.github/workflows/build-and-test-template.yml
--- a/.github/workflows/build-and-test-template.yml
+++ b/.github/workflows/build-and-test-template.yml
@@ -28,132 +28,132 @@ on:
         type: string
 
 jobs:
-  # build-devcontainer-linux:
-  #   name: "Build and test: ${{ matrix.host.os }}/${{ inputs.build-type }}"
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       host: [
-  #         { type: linux, os: ubuntu-latest,
-  #           build-options: "--build-tests -Xswiftc -enable-testing",
-  #           test-options: "--enable-code-coverage"
-  #         }
-  #       ]
-  #       # configuration: [ "debug", "release" ]
+  build-devcontainer-linux:
+    name: "Build and test: ${{ matrix.host.os }}/${{ inputs.build-type }}"
+    strategy:
+      fail-fast: false
+      matrix:
+        host: [
+          { type: linux, os: ubuntu-latest,
+            build-options: "--build-tests -Xswiftc -enable-testing",
+            test-options: "--enable-code-coverage"
+          }
+        ]
+        # configuration: [ "debug", "release" ]
 
-  #   runs-on: ${{ matrix.host.os }}
-  #   steps:
-  #   - uses: actions/checkout@v3
-  #     with:
-  #       submodules: 'true'
+    runs-on: ${{ matrix.host.os }}
+    steps:
+    - uses: actions/checkout@v3
+      with:
+        submodules: 'true'
 
-  #   - uses: actions/cache@v3
-  #     with:
-  #       path: .build
-  #       key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
-  #       restore-keys: |
-  #         ${{ runner.os }}-spm-
+    - uses: actions/cache@v3
+      with:
+        path: .build
+        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
+        restore-keys: |
+          ${{ runner.os }}-spm-
 
-  #   - name: Create artifact directory
-  #     run: mkdir -p /home/runner/work/hylo-lsp/hylo-lsp/artifacts
+    - name: Create artifact directory
+      run: mkdir -p /home/runner/work/hylo-lsp/hylo-lsp/artifacts
 
-  #   - name: Login to GitHub Container Registry
-  #     uses: docker/login-action@v3
-  #     with:
-  #       registry: ghcr.io
-  #       username: ${{ github.repository_owner }}
-  #       password: ${{ secrets.GITHUB_TOKEN }}
+    - name: Login to GitHub Container Registry
+      uses: docker/login-action@v3
+      with:
+        registry: ghcr.io
+        username: ${{ github.repository_owner }}
+        password: ${{ secrets.GITHUB_TOKEN }}
 
-    # - name: Build and Test
-    #   uses: devcontainers/ci@v0.3
+    - name: Build and Test
+      uses: devcontainers/ci@v0.3
+      with:
+        imageName: ghcr.io/koliyo/hylo-lsp-swift-devcontainer
+        cacheFrom: ghcr.io/koliyo/hylo-lsp-swift-devcontainer
+        runCmd: |
+          set -eo pipefail
+          swift build -c ${{ inputs.build-type }} ${{ matrix.host.build-options }}
+          BUILD_DIR=$(swift build -c ${{ inputs.build-type }} --show-bin-path)
+          echo "BUILD_DIR=$BUILD_DIR" >> $GITHUB_ENV
+          cp $BUILD_DIR/hylo-lsp-client $BUILD_DIR/hylo-lsp-server /artifacts/
+          # swift test -c ${{ inputs.build-type }} ${{ matrix.host.test-options }} |
+          #   tee testoutput.txt && (
+          #     (grep -q "[.']EndToEndTests[/. ]test_" testoutput.txt && grep -q "[.']HyloTests[/. ]test_" testoutput.txt) ||
+          #     (echo "error: generated tests failed to run; see
+          #     https://github.com/apple/swift-package-manager/issues/6595" && false) )
+
+    # - name: Check code coverage
+    #   uses: mattpolzin/swift-codecov-action@0.7.3
     #   with:
-    #     imageName: ghcr.io/koliyo/hylo-lsp-swift-devcontainer
-    #     cacheFrom: ghcr.io/koliyo/hylo-lsp-swift-devcontainer
-    #     runCmd: |
-    #       set -eo pipefail
-    #       swift build -c ${{ inputs.build-type }} ${{ matrix.host.build-options }}
-    #       BUILD_DIR=$(swift build -c ${{ inputs.build-type }} --show-bin-path)
-    #       echo "BUILD_DIR=$BUILD_DIR" >> $GITHUB_ENV
-    #       cp $BUILD_DIR/hylo-lsp-client $BUILD_DIR/hylo-lsp-server /artifacts/
-    #       # swift test -c ${{ inputs.build-type }} ${{ matrix.host.test-options }} |
-    #       #   tee testoutput.txt && (
-    #       #     (grep -q "[.']EndToEndTests[/. ]test_" testoutput.txt && grep -q "[.']HyloTests[/. ]test_" testoutput.txt) ||
-    #       #     (echo "error: generated tests failed to run; see
-    #       #     https://github.com/apple/swift-package-manager/issues/6595" && false) )
-
-  #   # - name: Check code coverage
-  #   #   uses: mattpolzin/swift-codecov-action@0.7.3
-  #   #   with:
-  #   #     SORT_ORDER: +cov
-  #   #     MINIMUM_COVERAGE: 84
-  #   #     CODECOV_JSON: .build/${{ inputs.build-type }}/codecov/*.json
+    #     SORT_ORDER: +cov
+    #     MINIMUM_COVERAGE: 84
+    #     CODECOV_JSON: .build/${{ inputs.build-type }}/codecov/*.json
 
 
-  #   - name: Upload Hylo LSP artifacts (${{ inputs.build-type }})
-  #     uses: actions/upload-artifact@v3
-  #     with:
-  #       name: hylo-lsp-artifacts-linux
-  #       path: |
-  #         artifacts/hylo-lsp-client
-  #         artifacts/hylo-lsp-server
+    - name: Upload Hylo LSP artifacts (${{ inputs.build-type }})
+      uses: actions/upload-artifact@v3
+      with:
+        name: hylo-lsp-artifacts-linux
+        path: |
+          artifacts/hylo-lsp-client
+          artifacts/hylo-lsp-server
 
-  # build-native-macos:
-  #   name: "Build and test: ${{ matrix.host.os }}/${{ inputs.build-type }}"
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       host: [
-  #         {
-  #           type: macos, os: macos-13,
-  #           build-options: "--build-tests -Xswiftc -enable-testing",
-  #           # No coverage support on MacOS
-  #           test-options: ""
-  #         }
-  #       ]
-  #       swift: [
-  #         { version: "5.9" }
-  #       ]
-  #       # configuration: [ $BUILD_TYPE ]
-  #       # configuration: [ "debug", "release" ]
+  build-native-macos:
+    name: "Build and test: ${{ matrix.host.os }}/${{ inputs.build-type }}"
+    strategy:
+      fail-fast: false
+      matrix:
+        host: [
+          {
+            type: macos, os: macos-13,
+            build-options: "--build-tests -Xswiftc -enable-testing",
+            # No coverage support on MacOS
+            test-options: ""
+          }
+        ]
+        swift: [
+          { version: "5.9" }
+        ]
+        # configuration: [ $BUILD_TYPE ]
+        # configuration: [ "debug", "release" ]
 
-  #   runs-on: ${{ matrix.host.os }}
-  #   steps:
-  #   - name: Checkout
-  #     uses: actions/checkout@v3
-  #     with:
-  #       submodules: 'true'
+    runs-on: ${{ matrix.host.os }}
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+      with:
+        submodules: 'true'
 
-  #   - name: Setup swift
-  #     uses: swift-actions/setup-swift@v1
-  #     with:
-  #       swift-version: ${{ matrix.swift.version }}
+    - name: Setup swift
+      uses: swift-actions/setup-swift@v1
+      with:
+        swift-version: ${{ matrix.swift.version }}
 
-  #   - run: swift --version
+    - run: swift --version
 
-    # - name: Build (${{ inputs.build-type }})
-    #   id: build
-    #   run: |
-    #     set -eo pipefail
-    #     swift build -c ${{ inputs.build-type }} ${{ matrix.host.build-options }}
-    #     BUILD_DIR=$(swift build -c ${{ inputs.build-type }} --show-bin-path)
-    #     echo "BUILD_DIR=$BUILD_DIR" >> $GITHUB_ENV
-    # - name: Test (${{ inputs.build-type }})
-    #   run: |
-    #     set -eo pipefail
-    #     export PKG_CONFIG_PATH=$PWD/hylo
-    #     swift test -c ${{ inputs.build-type }} ${{ matrix.host.test-options }} |
-    #       tee testoutput.txt && (
-    #         (grep -q "[.']EndToEndTests[/. ]test_" testoutput.txt && grep -q "[.']HyloTests[/. ]test_" testoutput.txt) ||
-    #         (echo "error: generated tests failed to run; see
-    #         https://github.com/apple/swift-package-manager/issues/6595" && false) )
+    - name: Build (${{ inputs.build-type }})
+      id: build
+      run: |
+        set -eo pipefail
+        swift build -c ${{ inputs.build-type }} ${{ matrix.host.build-options }}
+        BUILD_DIR=$(swift build -c ${{ inputs.build-type }} --show-bin-path)
+        echo "BUILD_DIR=$BUILD_DIR" >> $GITHUB_ENV
+    - name: Test (${{ inputs.build-type }})
+      run: |
+        set -eo pipefail
+        export PKG_CONFIG_PATH=$PWD/hylo
+        swift test -c ${{ inputs.build-type }} ${{ matrix.host.test-options }} |
+          tee testoutput.txt && (
+            (grep -q "[.']EndToEndTests[/. ]test_" testoutput.txt && grep -q "[.']HyloTests[/. ]test_" testoutput.txt) ||
+            (echo "error: generated tests failed to run; see
+            https://github.com/apple/swift-package-manager/issues/6595" && false) )
 
-  #   - name: Upload Hylo LSP artifacts (${{ inputs.build-type }})
-  #     uses: actions/upload-artifact@v3
-  #     with:
-  #       name: hylo-lsp-artifacts-mac
-  #       path: |
-  #         ${{ env.BUILD_DIR }}/hylo-lsp-client
-  #         ${{ env.BUILD_DIR }}/hylo-lsp-server
+    - name: Upload Hylo LSP artifacts (${{ inputs.build-type }})
+      uses: actions/upload-artifact@v3
+      with:
+        name: hylo-lsp-artifacts-mac
+        path: |
+          ${{ env.BUILD_DIR }}/hylo-lsp-client
+          ${{ env.BUILD_DIR }}/hylo-lsp-server
 
   build-native-windows:
     name: "Build and test: windows-latest/${{ inputs.build-type }}"
@@ -176,28 +176,29 @@ jobs:
     #     swift --version
     #     where swift
     #     Get-ChildItem -Recurse "C:\Program Files\Swift"
-    # - name: Build and copy support library
-    #   run: |
-    #     clang -c ./Library/Hylo/LibC.c -o HyloLibC.lib
-    #     xcopy HyloLibC.lib c:\program" "files\microsoft" "visual" "studio\2022\enterprise\vc\tools\msvc\${{ env.VCToolsVersion }}\lib\x64\
-    #   working-directory: hylo
 
-    # - name: Build (Release)
-    #   id: build
-    #   # continue-on-error: true
+    - name: Build and copy support library
+      run: |
+        clang -c ./Library/Hylo/LibC.c -o HyloLibC.lib
+        xcopy HyloLibC.lib c:\program" "files\microsoft" "visual" "studio\2022\enterprise\vc\tools\msvc\${{ env.VCToolsVersion }}\lib\x64\
+      working-directory: hylo
+
+    - name: Build (Release)
+      id: build
+      # continue-on-error: true
+      run: |
+        $BUILD_DIR = swift build -c ${{ inputs.build-type }} --show-bin-path
+        echo BUILD_DIR=$BUILD_DIR
+        echo BUILD_DIR=$BUILD_DIR >> $env:GITHUB_ENV
+        swift build -c ${{ inputs.build-type }}
+
+    - name: List build artifacts
+      run: Get-ChildItem -Recurse $env:BUILD_DIR
+
+    # - name: Copy artifacts
     #   run: |
     #     $BUILD_DIR = swift build -c ${{ inputs.build-type }} --show-bin-path
-    #     echo BUILD_DIR=$BUILD_DIR
-    #     echo BUILD_DIR=$BUILD_DIR >> $env:GITHUB_ENV
-    #     swift build -c ${{ inputs.build-type }}
-
-    # - name: List build artifacts
-    #   run: Get-ChildItem -Recurse $env:BUILD_DIR
-
-    # # - name: Copy artifacts
-    # #   run: |
-    # #     $BUILD_DIR = swift build -c ${{ inputs.build-type }} --show-bin-path
-    # #     xcopy $BUILD_DIR artifacts /I
+    #     xcopy $BUILD_DIR artifacts /I
 
     - name: Upload Hylo LSP artifacts (${{ inputs.build-type }})
       uses: actions/upload-artifact@v3
@@ -205,9 +206,8 @@ jobs:
         name: hylo-lsp-artifacts-windows
         path: |
           C:\Program Files\Swift\runtime-development\usr\bin
-        # ${{ env.BUILD_DIR }}
-        # ${{ env.BUILD_DIR }}/hylo-lsp-client.exe
-        # ${{ env.BUILD_DIR }}/hylo-lsp-server.exe
+          ${{ env.BUILD_DIR }}/hylo-lsp-client.exe
+          ${{ env.BUILD_DIR }}/hylo-lsp-server.exe
 
     # # - name: Retry on failure
     # #   continue-on-error: false
