.

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -109,43 +109,43 @@ jobs:
       with:
         submodules: 'true'
 
-    # - name: Setup swift
-    #   uses: swift-actions/setup-swift@v1
-    #   with:
-    #     swift-version: ${{ matrix.swift.version }}
+    - name: Setup swift
+      uses: swift-actions/setup-swift@v1
+      with:
+        swift-version: ${{ matrix.swift.version }}
 
-    # - run: swift --version
+    - run: swift --version
 
-    # - name: Setup LLVM
-    #   uses: KyleMayes/install-llvm-action@v1
-    #   with:
-    #     version: "15.0"
+    - name: Setup LLVM
+      uses: KyleMayes/install-llvm-action@v1
+      with:
+        version: "15.0"
 
-    # - run: llvm-config --version
+    - run: llvm-config --version
 
-    # - name: Generate LLVM pkgconfig file
-    #   run: |
-    #     set -eo pipefail
-    #     cd hylo
-    #     swift package resolve
-    #     .build/checkouts/Swifty-LLVM/Tools/make-pkgconfig.sh llvm.pc
-    #     cat llvm.pc
+    - name: Generate LLVM pkgconfig file
+      run: |
+        set -eo pipefail
+        cd hylo
+        swift package resolve
+        .build/checkouts/Swifty-LLVM/Tools/make-pkgconfig.sh llvm.pc
+        cat llvm.pc
 
-    # - name: Build (${{ matrix.configuration }})
-    #   run: |
-    #     set -eo pipefail
-    #     export PKG_CONFIG_PATH=$PWD/hylo
-    #     swift build -c ${{ matrix.configuration }} ${{ matrix.host.build-options }}
+    - name: Build (${{ matrix.configuration }})
+      run: |
+        set -eo pipefail
+        export PKG_CONFIG_PATH=$PWD/hylo
+        swift build -c ${{ matrix.configuration }} ${{ matrix.host.build-options }}
 
-    # - name: Test (${{ matrix.configuration }})
-    #   run: |
-    #     set -eo pipefail
-    #     export PKG_CONFIG_PATH=$PWD/hylo
-    #     swift test -c ${{ matrix.configuration }} ${{ matrix.host.test-options }} |
-    #       tee testoutput.txt && (
-    #         (grep -q "[.']EndToEndTests[/. ]test_" testoutput.txt && grep -q "[.']HyloTests[/. ]test_" testoutput.txt) ||
-    #         (echo "error: generated tests failed to run; see
-    #         https://github.com/apple/swift-package-manager/issues/6595" && false) )
+    - name: Test (${{ matrix.configuration }})
+      run: |
+        set -eo pipefail
+        export PKG_CONFIG_PATH=$PWD/hylo
+        swift test -c ${{ matrix.configuration }} ${{ matrix.host.test-options }} |
+          tee testoutput.txt && (
+            (grep -q "[.']EndToEndTests[/. ]test_" testoutput.txt && grep -q "[.']HyloTests[/. ]test_" testoutput.txt) ||
+            (echo "error: generated tests failed to run; see
+            https://github.com/apple/swift-package-manager/issues/6595" && false) )
 
     - uses: actions/setup-node@v3
       with:
@@ -153,12 +153,12 @@ jobs:
 
     - name: Package VSCode extension (${{ matrix.configuration }})
       run: |
-        # BUILD_DIR=$(swift build -c ${{ matrix.configuration }} --show-bin-path)
-        # mkdir -p hylo-lsp-vs-code/bin/mac/arm64
-        # cp -fv $BUILD_DIR/hylo-lsp-server hylo-lsp-vs-code/bin/mac/arm64
+        BUILD_DIR=$(swift build -c ${{ matrix.configuration }} --show-bin-path)
+        mkdir -p hylo-lsp-vs-code/bin/mac/arm64
+        cp -fv $BUILD_DIR/hylo-lsp-server hylo-lsp-vs-code/bin/mac/arm64
         cd hylo-vscode-extension
         npm install
-        npm run vscode:all
+        npm run vscode:package
 
   # build-native-windows:
   #   name: "Native, no testing: windows-latest/release"
